import { useState, type ReactNode } from 'react'
import { Show, SignInButton, SignUpButton, UserButton } from '@clerk/react'

type IconName = 'arrow'|'check'|'code'|'calendar'|'spark'|'target'|'close'|'clock'|'video'
function Icon({name,size=20}:{name:IconName,size?:number}){
  const p:Record<IconName,ReactNode>={arrow:<><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></>,check:<path d="m5 12 4 4L19 6"/>,code:<><path d="m8 9-3 3 3 3M16 9l3 3-3 3M14 5l-4 14"/></>,calendar:<><path d="M8 2v4m8-4v4M3 10h18"/><rect x="3" y="4" width="18" height="18" rx="3"/></>,spark:<path d="m12 3-1.3 4.2a5 5 0 0 1-3.3 3.3L3 12l4.4 1.5a5 5 0 0 1 3.2 3.2L12 21l1.4-4.3a5 5 0 0 1 3.2-3.2L21 12l-4.4-1.5a5 5 0 0 1-3.3-3.3L12 3Z"/>,target:<><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="4"/></>,close:<path d="m6 6 12 12M18 6 6 18"/>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,video:<><rect x="3" y="6" width="13" height="12" rx="2"/><path d="m16 10 5-3v10l-5-3"/></>}
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{p[name]}</svg>
}
function AuthAction({children,small=false,clerkEnabled,onPreview}:{children:ReactNode,small?:boolean,clerkEnabled:boolean,onPreview:()=>void}){
  const cls=small?'nav-cta':'button primary'
  if(!clerkEnabled)return <button className={cls} onClick={onPreview}>{children}</button>
  return <><Show when="signed-out"><SignUpButton mode="modal"><button className={cls}>{children}</button></SignUpButton></Show><Show when="signed-in">{small?<UserButton/>:<a className={cls} href="#how">يلا نبدأ <Icon name="arrow"/></a>}</Show></>
}

export default function App({clerkEnabled}:{clerkEnabled:boolean}){
  const [setup,setSetup]=useState(false)
  return <div className="app">
    <header><nav className="container nav"><a href="#top" className="brand"><b><Icon name="code"/></b>سلم<span>.</span></a><div className="links"><a href="#how">بنشتغل إزاي؟</a><a href="#about">عن المبادرة</a></div><div className="auth">{clerkEnabled?<><Show when="signed-out"><SignInButton mode="modal"><button className="login">دخول</button></SignInButton></Show><Show when="signed-in"><UserButton/></Show></>:<button className="login" onClick={()=>setSetup(true)}>دخول</button>}<AuthAction small clerkEnabled={clerkEnabled} onPreview={()=>setSetup(true)}>احجز سيشن <Icon name="arrow" size={16}/></AuthAction></div></nav></header>
    <main id="top"><section className="hero"><div className="container hero-grid"><div className="copy"><div className="eyebrow"><i/>عشان طريقك في التِك يستاهل بداية أقوى</div><h1>خبرتك في التِك<br/>تستاهل <em>فرصة بجد.</em></h1><p>سيشنز فردية ببلاش مع ناس خبرة من مجتمع التِك المصري، تساعدك تطوّر مهاراتك، تحدد طريقك، وتجهّز لخطوتك الجاية بثقة.</p><div className="actions"><AuthAction clerkEnabled={clerkEnabled} onPreview={()=>setSetup(true)}>احجز سيشن ببلاش <Icon name="arrow"/></AuthAction><a href="#how" className="discover"><span><Icon name="spark" size={16}/></span>شوف هنساعدك إزاي</a></div></div>
    <div className="visual"><div className="ring a"/><div className="ring b"/><div className="codebox"><div className="codebar"><i/><i/><i/><span>career_path.ts</span></div><pre><span>01</span> <b>const</b> nextStep = {'{'}{`\n`}<span>02</span>   skills: <em>'strong'</em>,{`\n`}<span>03</span>   guidance: <em>'expert'</em>,{`\n`}<span>04</span>   confidence: <strong>true</strong>{`\n`}<span>05</span> {'}'};</pre><footer><i/> سيشن لايف <span>45 دقيقة</span></footer></div><div className="goal"><span><Icon name="target"/></span><div><small>هدفك الجاي</small><strong>اتجهّز للإنترفيو</strong></div><b>78%</b></div></div></div></section>
    <section className="audience"><div className="container"><p>معمولة ليك لو إنت</p><div>{['خريج حاسبات أو هندسة','لسه بادئ في البرمجة','عايز تعمل كارير شيفت','بتحضّر لإنترفيو تِكنيكال'].map(x=><span key={x}><Icon name="check" size={16}/>{x}</span>)}</div></div></section>
    <section className="section how" id="how"><div className="container"><div className="heading"><span>من غير لف ولا تعقيد</span><h2>3 خطوات بينك وبين<br/><em>الخطوة اللي جاية</em></h2><p>قول لنا محتاج إيه، اقعد مع حد فاهم، واطلع بخطة واضحة تقدر تبدأ فيها فورًا.</p></div><div className="steps">{[["01","target","قول لنا هدفك","عرّفنا إنت واقف فين، إيه اللي معطّلك، وعايز توصل لإيه."],["02","calendar","اختار معادك","احجز الوقت اللي يناسبك، والسيشن علينا بالكامل."],["03","spark","ابدأ تتحرّك","كلام واضح، فيدباك صريح، وخطوات عملية تمشي عليها."]].map(s=><article key={s[0]}><small>{s[0]}</small><i><Icon name={s[1] as IconName} size={26}/></i><h3>{s[2]}</h3><p>{s[3]}</p></article>)}</div></div></section>
    <section className="cta" id="about"><div className="container cta-box"><div><span>خطوتك الجاية بتبدأ من هنا</span><h2>ما تستناش الفرصة.<br/>جهّز نفسك ليها.</h2><p>45 دقيقة ممكن تغيّر نظرتك لكاريرك وتخلّيك عارف تبدأ منين.</p><div className="cta-actions"><AuthAction clerkEnabled={clerkEnabled} onPreview={()=>setSetup(true)}>احجز سيشن ببلاش <Icon name="arrow"/></AuthAction><small><Icon name="clock"/> ببلاش تمامًا</small><small><Icon name="video"/> أونلاين</small></div></div><div className="terminal"><div><i/><i/><i/></div><pre>$ sellam --start{`\n\n`}✓ حدّدنا هدفك{`\n`}✓ جهّزنا خطتك{`\n\n`}<b>جاهز للخطوة الجاية؟ ▌</b></pre></div></div></section></main>
    <footer className="site-footer"><div className="container"><a className="brand" href="#top"><b><Icon name="code"/></b>سلم<span>.</span></a><p>مبادرة مصرية معمولة عشان مجتمع التِك يكبر ويسند بعضه.</p><small>© 2026 سلم</small></div></footer>
    {setup&&<div className="modal" onClick={()=>setSetup(false)}><div onClick={e=>e.stopPropagation()}><button onClick={()=>setSetup(false)}><Icon name="close"/></button><i><Icon name="code" size={27}/></i><h3>فعّل Clerk عشان تبدأ الحجز</h3><p>حط مفتاح النشر في ملف <code>.env.local</code> عشان التسجيل والحجز يشتغلوا.</p><code>VITE_CLERK_PUBLISHABLE_KEY=pk_test_...</code><button className="button primary" onClick={()=>setSetup(false)}>تمام</button></div></div>}
  </div>
}
