import { useState, type ReactNode } from 'react'
import { Show, SignInButton, SignUpButton, UserButton } from '@clerk/react'

type IconName = 'arrow'|'check'|'code'|'calendar'|'spark'|'target'|'menu'|'close'|'clock'|'video'
function Icon({name,size=20}:{name:IconName,size?:number}){
  const p:Record<IconName,ReactNode>={arrow:<><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></>,check:<path d="m5 12 4 4L19 6"/>,code:<><path d="m8 9-3 3 3 3M16 9l3 3-3 3M14 5l-4 14"/></>,calendar:<><path d="M8 2v4m8-4v4M3 10h18"/><rect x="3" y="4" width="18" height="18" rx="3"/></>,spark:<path d="m12 3-1.3 4.2a5 5 0 0 1-3.3 3.3L3 12l4.4 1.5a5 5 0 0 1 3.2 3.2L12 21l1.4-4.3a5 5 0 0 1 3.2-3.2L21 12l-4.4-1.5a5 5 0 0 1-3.3-3.3L12 3Z"/>,target:<><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="4"/></>,menu:<path d="M4 7h16M4 12h16M4 17h16"/>,close:<path d="m6 6 12 12M18 6 6 18"/>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,video:<><rect x="3" y="6" width="13" height="12" rx="2"/><path d="m16 10 5-3v10l-5-3"/></>}
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{p[name]}</svg>
}
const mentors=[['سن','سارة النجار','مهندسة برمجيات أولى','Google','mint'],['مع','محمد العتيبي','قائد فريق هندسي','Careem','blue'],['لي','ليان يوسف','مديرة منتجات تقنية','Amazon','coral']]

function AuthAction({children,small=false,clerkEnabled,onPreview}:{children:ReactNode,small?:boolean,clerkEnabled:boolean,onPreview:()=>void}){
  const cls=small?'nav-cta':'button primary'
  if(!clerkEnabled)return <button className={cls} onClick={onPreview}>{children}</button>
  return <><Show when="signed-out"><SignUpButton mode="modal"><button className={cls}>{children}</button></SignUpButton></Show><Show when="signed-in">{small?<UserButton/>:<a className={cls} href="#mentors">استكشف المرشدين <Icon name="arrow"/></a>}</Show></>
}

export default function App({clerkEnabled}:{clerkEnabled:boolean}){
  const [menu,setMenu]=useState(false),[setup,setSetup]=useState(false)
  return <div className="app">
    <header><nav className="container nav"><a href="#top" className="brand"><b><Icon name="code"/></b>مُرشد<span>.</span></a><div className={`links ${menu?'open':''}`}><button className="close" onClick={()=>setMenu(false)}><Icon name="close"/></button><a href="#how">كيف تعمل؟</a><a href="#mentors">المرشدون</a><a href="#about">عن المبادرة</a></div><div className="auth">{clerkEnabled?<><Show when="signed-out"><SignInButton mode="modal"><button className="login">تسجيل الدخول</button></SignInButton></Show><Show when="signed-in"><UserButton/></Show></>:<button className="login" onClick={()=>setSetup(true)}>تسجيل الدخول</button>}<AuthAction small clerkEnabled={clerkEnabled} onPreview={()=>setSetup(true)}>احجز جلستك <Icon name="arrow" size={16}/></AuthAction></div><button className="hamburger" onClick={()=>setMenu(true)}><Icon name="menu"/></button></nav></header>
    <main id="top"><section className="hero"><div className="container hero-grid"><div className="copy"><div className="eyebrow"><i/>لأن طريقك المهني يستحق بداية أقوى</div><h1>خبرتك التقنية<br/>تستحق <em>فرصة حقيقية.</em></h1><p>جلسات فردية مجانية مع خبراء في مجال التقنية، تساعدك على تطوير مهاراتك، رسم مسارك المهني، والاستعداد لخطوتك القادمة بثقة.</p><div className="actions"><AuthAction clerkEnabled={clerkEnabled} onPreview={()=>setSetup(true)}>احجز جلستك المجانية <Icon name="arrow"/></AuthAction><a href="#how" className="discover"><span><Icon name="spark" size={16}/></span>اكتشف كيف نساعدك</a></div><div className="trust"><div className="faces"><b>سن</b><b>مع</b><b>لي</b><b>+40</b></div><div><strong>★★★★★</strong><small>أكثر من <b>1,200</b> جلسة إرشادية ناجحة</small></div></div></div>
    <div className="visual"><div className="ring a"/><div className="ring b"/><div className="codebox"><div className="codebar"><i/><i/><i/><span>career_path.ts</span></div><pre><span>01</span> <b>const</b> nextStep = {'{'}{`\n`}<span>02</span>   skills: <em>'strong'</em>,{`\n`}<span>03</span>   guidance: <em>'expert'</em>,{`\n`}<span>04</span>   confidence: <strong>true</strong>{`\n`}<span>05</span> {'}'};</pre><footer><i/> جلسة مباشرة <span>45 دقيقة</span></footer></div><div className="goal"><span><Icon name="target"/></span><div><small>الهدف القادم</small><strong>استعد لمقابلتك</strong></div><b>78%</b></div></div></div></section>
    <section className="audience"><div className="container"><p>مصممة لك إذا كنت</p><div>{['خريج تخصص تقني','مبرمجًا في بداية مسيرتك','تبحث عن نقلة مهنية','تستعد لمقابلة تقنية'].map(x=><span key={x}><Icon name="check" size={16}/>{x}</span>)}</div></div></section>
    <section className="section how" id="how"><div className="container"><div className="heading"><span>ببساطة وبدون تعقيد</span><h2>ثلاث خطوات تفصلك عن<br/><em>نسخة أفضل منك</em></h2><p>اختر ما تحتاجه، التقِ بخبير، واخرج بخطة واضحة يمكنك تطبيقها فورًا.</p></div><div className="steps">{[["01","target","حدد هدفك","أخبرنا عن مهاراتك، تحدياتك، وما تريد الوصول إليه."],["02","calendar","اختر مرشدك وموعدك","تصفح خبرات المرشدين واحجز الوقت الأنسب لك مجانًا."],["03","spark","ابدأ التغيير","جلسة مركزة، ملاحظات صريحة، وخطوات عملية لمسارك."]].map(s=><article key={s[0]}><small>{s[0]}</small><i><Icon name={s[1] as IconName} size={26}/></i><h3>{s[2]}</h3><p>{s[3]}</p></article>)}</div></div></section>
    <section className="section mentor-section" id="mentors"><div className="container"><div className="split"><div><span>خبرة تستحق الثقة</span><h2>تعلّم ممن<br/><em>سبقوك بخطوة.</em></h2></div><p>مرشدون من شركات تقنية رائدة، تطوعوا بوقتهم وخبرتهم ليدعموا الجيل القادم من صناع التقنية.</p></div><div className="mentor-grid">{mentors.map(m=><article key={m[1]}><div className={`portrait ${m[4]}`}><b>{m[0]}</b><small>● متاح للحجز</small></div><div className="mentor-info"><small>{m[2]}</small><h3>{m[1]}</h3><strong>{m[3]}</strong></div></article>)}</div><a className="button outline" href="#top">عرض جميع المرشدين <Icon name="arrow"/></a></div></section>
    <section className="cta" id="about"><div className="container cta-box"><div><span>خطوتك التالية تبدأ من هنا</span><h2>لا تنتظر الفرصة.<br/>استعد لها.</h2><p>45 دقيقة قد تغيّر الطريقة التي ترى بها مسارك بالكامل.</p><div className="cta-actions"><AuthAction clerkEnabled={clerkEnabled} onPreview={()=>setSetup(true)}>احجز جلسة مجانية <Icon name="arrow"/></AuthAction><small><Icon name="clock"/> مجانية بالكامل</small><small><Icon name="video"/> عن بُعد</small></div></div><div className="terminal"><div><i/><i/><i/></div><pre>$ mentor --start{`\n\n`}✓ تم اختيار الهدف{`\n`}✓ تم إيجاد المرشد المناسب{`\n\n`}<b>جاهز لخطوتك القادمة؟ ▌</b></pre></div></div></section></main>
    <footer className="site-footer"><div className="container"><a className="brand" href="#top"><b><Icon name="code"/></b>مُرشد<span>.</span></a><p>مبادرة عربية غير ربحية، نصنع أثرًا بجلسة واحدة في كل مرة.</p><small>© 2026 مُرشد</small></div></footer>
    {setup&&<div className="modal" onClick={()=>setSetup(false)}><div onClick={e=>e.stopPropagation()}><button onClick={()=>setSetup(false)}><Icon name="close"/></button><i><Icon name="code" size={27}/></i><h3>فعّل Clerk لبدء الحجز</h3><p>أضف مفتاح النشر إلى ملف <code>.env.local</code> لتفعيل التسجيل والحجز.</p><code>VITE_CLERK_PUBLISHABLE_KEY=pk_test_...</code><button className="button primary" onClick={()=>setSetup(false)}>فهمت</button></div></div>}
  </div>
}
